graph TD
Frontend --> Backend
Frontend --> Other
Frontend --> Infrastructure
Frontend --> Tooling
Backend --> Other
Backend --> Frontend
Tooling --> Backend
Core --> Backend
Core --> Frontend
Other --> Backend
Other --> Frontend
Other --> Tooling
Other --> Infrastructure
Infrastructure --> Backend
Infrastructure --> Frontend
Backend --> Infrastructure
Backend --> Tooling
Tooling --> Infrastructure
Tooling --> Other
Tooling --> Frontend