
graph TD
app --> catalog
app --> catalog-common
backend --> catalog-common
backend --> catalog
app --> user-settings/alpha
app --> home/alpha
app --> home-react/alpha
app --> home
app --> techdocs
app --> app-visualizer
app --> catalog-import
app --> kubernetes/alpha
app --> catalog-react/alpha
app --> catalog/alpha
app --> app/alpha
app --> search
app --> notifications
app --> user-settings
app-defaults --> permission
app-legacy --> scaffolder/alpha
app-legacy --> scaffolder
app-legacy --> api-docs
app-legacy --> catalog
app-legacy --> catalog-graph
app-legacy --> catalog-import
app-legacy --> home
app-legacy --> search
app-legacy --> techdocs
app-legacy --> techdocs-module-addons-contrib
app-legacy --> user-settings
app-legacy --> signals
app-legacy --> permission
app-legacy --> catalog-common/alpha
app-legacy --> devtools
app-legacy --> catalog-unprocessed-entities
app-legacy --> notifications
app-legacy --> mui-to-bui
app-legacy --> catalog-react/testUtils
app-legacy --> kubernetes
app-legacy --> kubernetes-cluster
app-legacy --> org
app-legacy --> scaffolder-react/alpha
app-legacy --> auth
backend --> auth-backend-module-github-provider
backend --> auth
backend-defaults --> permission-common
backend-defaults --> events
backend-defaults --> auth
backend-defaults --> permission
backend-dynamic-feature-service --> app
backend-plugin-api --> permission-common
backend-plugin-api --> permission
backend-test-utils --> events
backend-test-utils --> permission-common
catalog-client --> catalog-common
cli-module-new --> catalog
cli-module-new --> scaffolder-node-test-utils
cli-module-new --> scaffolder
core-compat-api --> catalog
core-compat-api --> catalog-react/alpha
core-compat-api --> catalog/alpha
core-compat-api --> catalog-react/testUtils
core-compat-api --> app
create-app --> catalog/alpha
create-app --> app
create-app --> search
create-app --> user-settings
create-app --> notifications
create-app --> api-docs
create-app --> catalog
create-app --> catalog-import
create-app --> scaffolder
create-app --> org
create-app --> techdocs
create-app --> techdocs-module-addons-contrib
create-app --> catalog-graph
create-app --> permission
create-app --> catalog-common/alpha
create-app --> signals
create-app --> kubernetes
dev-utils --> catalog
frontend-app-api --> app
frontend-app-api --> permission-common
frontend-defaults --> app
frontend-defaults --> permission
frontend-defaults --> permission-common
frontend-dev-utils --> app
frontend-test-utils --> permission
frontend-test-utils --> permission-common
frontend-test-utils --> app
scaffolder-internal --> scaffolder-react/alpha
techdocs-cli --> techdocs
techdocs-cli-embedded-app --> techdocs-react/alpha
techdocs-cli-embedded-app --> techdocs
techdocs-cli-embedded-app --> techdocs/alpha
techdocs-cli-embedded-app --> catalog/alpha
techdocs-cli-embedded-app --> app
test-utils --> permission-common
test-utils --> permission
api-docs --> catalog
api-docs --> catalog-react/testUtils
api-docs --> catalog-react/alpha
api-docs --> permission
api-docs --> catalog-common/alpha
app --> permission
app-backend --> app
auth-backend --> catalog-node/testUtils
auth-backend --> catalog
auth-backend --> auth-backend-module-guest-provider
auth-backend --> auth
auth-backend-module-atlassian-provider --> auth
auth-backend-module-auth0-provider --> auth-backend
auth-backend-module-auth0-provider --> auth
auth-backend-module-aws-alb-provider --> auth
auth-backend-module-azure-easyauth-provider --> auth
auth-backend-module-azure-easyauth-provider --> auth-backend
auth-backend-module-bitbucket-provider --> auth
auth-backend-module-bitbucket-server-provider --> auth-backend
auth-backend-module-bitbucket-server-provider --> auth
auth-backend-module-cloudflare-access-provider --> auth
auth-backend-module-gcp-iap-provider --> auth
auth-backend-module-github-provider --> auth
auth-backend-module-gitlab-provider --> auth
auth-backend-module-google-provider --> auth
auth-backend-module-guest-provider --> auth
auth-backend-module-microsoft-provider --> auth-backend
auth-backend-module-microsoft-provider --> auth
auth-backend-module-oauth2-provider --> auth
auth-backend-module-oauth2-proxy-provider --> auth
auth-backend-module-oidc-provider --> auth
auth-backend-module-okta-provider --> auth
auth-backend-module-onelogin-provider --> auth
auth-backend-module-openshift-provider --> auth-backend
auth-backend-module-openshift-provider --> auth
auth-backend-module-pinniped-provider --> auth-backend
auth-backend-module-pinniped-provider --> auth
auth-backend-module-vmware-cloud-provider --> auth
catalog --> catalog-react/alpha
catalog --> catalog-common/alpha
catalog --> catalog-react/testUtils
catalog --> search-react/alpha
catalog --> permission
catalog --> permission-common
catalog --> techdocs-common
catalog --> techdocs
catalog --> scaffolder-common
catalog --> scaffolder-common/alpha
catalog --> search-common
catalog --> search
catalog-backend --> catalog-node/alpha
catalog-backend --> scaffolder-common/alpha
catalog-backend --> catalog-node/testUtils
catalog-backend --> catalog
catalog-backend --> events
catalog-backend --> catalog-common
catalog-backend --> permission
catalog-backend --> catalog-common/alpha
catalog-backend --> permission-common
catalog-backend-module-aws --> kubernetes-common
catalog-backend-module-aws --> catalog
catalog-backend-module-aws --> catalog-common
catalog-backend-module-azure --> catalog-node/alpha
catalog-backend-module-azure --> events
catalog-backend-module-azure --> catalog
catalog-backend-module-azure --> catalog-common
catalog-backend-module-backstage-openapi --> catalog
catalog-backend-module-bitbucket-cloud --> catalog-node/alpha
catalog-backend-module-bitbucket-cloud --> events
catalog-backend-module-bitbucket-cloud --> catalog
catalog-backend-module-bitbucket-cloud --> events-backend-test-utils
catalog-backend-module-bitbucket-cloud --> bitbucket-cloud-common
catalog-backend-module-bitbucket-cloud --> catalog-node/testUtils
catalog-backend-module-bitbucket-cloud --> catalog-common
catalog-backend-module-bitbucket-server --> catalog
catalog-backend-module-bitbucket-server --> events-backend-test-utils
catalog-backend-module-bitbucket-server --> events
catalog-backend-module-bitbucket-server --> catalog-node/testUtils
catalog-backend-module-bitbucket-server --> catalog-common
catalog-backend-module-gcp --> catalog
catalog-backend-module-gcp --> kubernetes-common
catalog-backend-module-gerrit --> catalog
catalog-backend-module-gerrit --> catalog-common
catalog-backend-module-gitea --> catalog
catalog-backend-module-gitea --> catalog-common
catalog-backend-module-github --> catalog-node/testUtils
catalog-backend-module-github --> catalog
catalog-backend-module-github --> catalog-node/alpha
catalog-backend-module-github --> events
catalog-backend-module-github --> catalog-common
catalog-backend-module-github-org --> catalog
catalog-backend-module-github-org --> catalog-backend-module-github
catalog-backend-module-github-org --> events
catalog-backend-module-gitlab --> catalog-node/alpha
catalog-backend-module-gitlab --> events
catalog-backend-module-gitlab --> catalog
catalog-backend-module-gitlab --> events-backend-test-utils
catalog-backend-module-gitlab --> catalog-common
catalog-backend-module-gitlab-org --> catalog-backend-module-gitlab
catalog-backend-module-gitlab-org --> catalog
catalog-backend-module-gitlab-org --> events-backend-test-utils
catalog-backend-module-gitlab-org --> events
catalog-backend-module-incremental-ingestion --> catalog
catalog-backend-module-incremental-ingestion --> events
catalog-backend-module-ldap --> catalog
catalog-backend-module-ldap --> catalog-common
catalog-backend-module-logs --> events-backend-test-utils
catalog-backend-module-logs --> events
catalog-backend-module-logs --> catalog-backend
catalog-backend-module-msgraph --> catalog
catalog-backend-module-msgraph --> catalog-common
catalog-backend-module-openapi --> catalog
catalog-backend-module-openapi --> catalog-common
catalog-backend-module-puppetdb --> catalog
catalog-backend-module-scaffolder-entity-model --> catalog
catalog-backend-module-scaffolder-entity-model --> scaffolder-common
catalog-backend-module-scaffolder-entity-model --> catalog-common
catalog-backend-module-unprocessed --> catalog-unprocessed-entities-common
catalog-backend-module-unprocessed --> permission-common
catalog-common --> permission-common
catalog-common --> search-common
catalog-graph --> catalog
catalog-graph --> catalog-react/testUtils
catalog-graph --> catalog-react/alpha
catalog-import --> catalog
catalog-import --> permission
catalog-import --> catalog-common/alpha
catalog-import --> catalog-react/testUtils
catalog-import --> catalog-common
catalog-import --> catalog-import/alpha
catalog-node --> catalog-common/alpha
catalog-node --> permission
catalog-node --> catalog
catalog-node --> catalog-common
catalog-react --> catalog
catalog-react --> catalog-react/testUtils
catalog-react --> scaffolder-common
catalog-react --> catalog-common/alpha
catalog-react --> permission
catalog-react --> permission-common
catalog-unprocessed-entities --> catalog-unprocessed-entities-common
catalog-unprocessed-entities-common --> permission-common
devtools --> devtools-common
devtools --> devtools-common/alpha
devtools --> permission
devtools-backend --> devtools-common
devtools-backend --> devtools-common/alpha
devtools-backend --> permission-common
devtools-common --> permission-common
events-backend --> events
events-backend --> events-node/alpha
events-backend --> events-backend-test-utils
events-backend-module-aws-sqs --> events-backend-test-utils
events-backend-module-aws-sqs --> events
events-backend-module-azure --> events-backend-test-utils
events-backend-module-azure --> events
events-backend-module-bitbucket-cloud --> events-backend-test-utils
events-backend-module-bitbucket-cloud --> events
events-backend-module-bitbucket-server --> events-backend-test-utils
events-backend-module-bitbucket-server --> events
events-backend-module-gerrit --> events-backend-test-utils
events-backend-module-gerrit --> events
events-backend-module-github --> events
events-backend-module-github --> events-backend-test-utils
events-backend-module-github --> events-node/alpha
events-backend-module-gitlab --> events
events-backend-module-gitlab --> events-backend-test-utils
events-backend-module-gitlab --> events-node/alpha
events-backend-module-google-pubsub --> events
events-backend-module-kafka --> events
events-backend-module-kafka --> events-backend-test-utils
events-backend-test-utils --> events
events-node --> events
example-todo-list-common --> permission-common
home --> catalog
home --> catalog-react/testUtils
home --> catalog/alpha
home --> home-react/alpha
kubernetes --> catalog
kubernetes --> kubernetes-common
kubernetes --> permission
kubernetes --> catalog-react/alpha
kubernetes-backend --> kubernetes
kubernetes-backend --> kubernetes-common
kubernetes-backend --> permission-common
kubernetes-backend --> catalog-node/testUtils
kubernetes-backend --> catalog
kubernetes-backend --> permission
kubernetes-cluster --> catalog
kubernetes-cluster --> kubernetes
kubernetes-cluster --> kubernetes-common
kubernetes-cluster --> permission
kubernetes-common --> permission-common
kubernetes-common --> kubernetes
kubernetes-node --> kubernetes-common
kubernetes-node --> kubernetes-backend
kubernetes-node --> kubernetes
kubernetes-react --> kubernetes-common
mcp-actions-backend --> catalog-node/testUtils
mcp-actions-backend --> mcp-actions-backend/package.json
notifications --> signals
notifications --> notifications-common
notifications-backend --> notifications
notifications-backend --> notifications-common
notifications-backend --> signals
notifications-backend --> catalog
notifications-backend --> catalog-node/testUtils
notifications-backend-module-email --> notifications-common
notifications-backend-module-email --> catalog
notifications-backend-module-email --> notifications
notifications-backend-module-email --> catalog-node/testUtils
notifications-backend-module-slack --> notifications-common
notifications-backend-module-slack --> catalog-node/testUtils
notifications-backend-module-slack --> notifications
notifications-backend-module-slack --> catalog
notifications-node --> notifications-common
org --> catalog-react/testUtils
org --> catalog-react/alpha
org --> catalog
org --> catalog-common/alpha
org --> permission
org-react --> catalog
org-react --> catalog-react/testUtils
permission-backend --> permission
permission-backend --> permission-node/alpha
permission-backend --> permission-common
permission-backend --> auth
permission-backend-module-policy-allow-all --> permission-node/alpha
permission-backend-module-policy-allow-all --> permission-common
permission-backend-module-policy-allow-all --> permission
permission-node --> permission-common
permission-node --> permission
permission-node --> auth
permission-react --> permission-common
proxy-backend --> proxy-node/alpha
scaffolder --> catalog
scaffolder --> scaffolder-react/alpha
scaffolder --> permission
scaffolder --> scaffolder-common/alpha
scaffolder --> catalog-common/alpha
scaffolder --> catalog-react/testUtils
scaffolder --> techdocs-common
scaffolder --> scaffolder-common
scaffolder --> techdocs
scaffolder --> catalog-react/alpha
scaffolder --> permission-common
scaffolder --> scaffolder/alpha
scaffolder-backend --> scaffolder-node/testUtils
scaffolder-backend --> scaffolder
scaffolder-backend --> scaffolder-common
scaffolder-backend --> scaffolder-node/alpha
scaffolder-backend --> scaffolder-node-test-utils
scaffolder-backend --> catalog-node/testUtils
scaffolder-backend --> catalog
scaffolder-backend --> permission-common
scaffolder-backend --> events
scaffolder-backend --> permission
scaffolder-backend --> scaffolder-common/alpha
scaffolder-backend-module-azure --> scaffolder
scaffolder-backend-module-azure --> scaffolder-node-test-utils
scaffolder-backend-module-bitbucket-cloud --> scaffolder
scaffolder-backend-module-bitbucket-cloud --> scaffolder-node-test-utils
scaffolder-backend-module-bitbucket-cloud --> bitbucket-cloud-common
scaffolder-backend-module-bitbucket-cloud --> scaffolder-node/alpha
scaffolder-backend-module-bitbucket-server --> scaffolder
scaffolder-backend-module-bitbucket-server --> scaffolder-node-test-utils
scaffolder-backend-module-confluence-to-markdown --> scaffolder
scaffolder-backend-module-confluence-to-markdown --> scaffolder-node-test-utils
scaffolder-backend-module-cookiecutter --> scaffolder
scaffolder-backend-module-cookiecutter --> scaffolder-node-test-utils
scaffolder-backend-module-gcp --> scaffolder-node/alpha
scaffolder-backend-module-gerrit --> scaffolder
scaffolder-backend-module-gerrit --> scaffolder-node-test-utils
scaffolder-backend-module-gitea --> scaffolder
scaffolder-backend-module-gitea --> scaffolder-node-test-utils
scaffolder-backend-module-github --> scaffolder
scaffolder-backend-module-github --> scaffolder-node-test-utils
scaffolder-backend-module-github --> catalog-node/testUtils
scaffolder-backend-module-github --> catalog
scaffolder-backend-module-github --> scaffolder-node/alpha
scaffolder-backend-module-gitlab --> scaffolder-node-test-utils
scaffolder-backend-module-gitlab --> scaffolder
scaffolder-backend-module-gitlab --> scaffolder-node/alpha
scaffolder-backend-module-notifications --> notifications
scaffolder-backend-module-notifications --> scaffolder
scaffolder-backend-module-notifications --> scaffolder-node-test-utils
scaffolder-backend-module-notifications --> notifications-common
scaffolder-backend-module-rails --> scaffolder
scaffolder-backend-module-rails --> scaffolder-node-test-utils
scaffolder-backend-module-sentry --> scaffolder-node-test-utils
scaffolder-backend-module-sentry --> scaffolder
scaffolder-backend-module-yeoman --> scaffolder-node-test-utils
scaffolder-backend-module-yeoman --> scaffolder
scaffolder-common --> permission-common
scaffolder-node --> scaffolder-common
scaffolder-node --> scaffolder-node/alpha
scaffolder-node --> scaffolder
scaffolder-node --> permission
scaffolder-node --> scaffolder-common/alpha
scaffolder-node --> permission-common
scaffolder-node-test-utils --> scaffolder
scaffolder-node-test-utils --> scaffolder-node/alpha
scaffolder-react --> scaffolder-common
scaffolder-react --> scaffolder
scaffolder-react --> permission
scaffolder-react --> scaffolder-common/alpha
scaffolder-react --> catalog
scaffolder-react --> permission-common
scaffolder-react --> catalog-react/testUtils
search --> catalog
search --> search-common
search --> search-react/alpha
search-backend --> search-backend-node/alpha
search-backend --> permission-common
search-backend --> search-common
search-backend-module-catalog --> catalog-common
search-backend-module-catalog --> catalog-node/testUtils
search-backend-module-catalog --> search-backend
search-backend-module-catalog --> catalog-common/alpha
search-backend-module-catalog --> catalog
search-backend-module-catalog --> permission-common
search-backend-module-catalog --> search-common
search-backend-module-catalog --> search-backend-node/alpha
search-backend-module-elasticsearch --> search-common
search-backend-module-elasticsearch --> search-backend
search-backend-module-elasticsearch --> search-backend-node/alpha
search-backend-module-explore --> search-backend
search-backend-module-explore --> search-common
search-backend-module-explore --> search-backend-node/alpha
search-backend-module-pg --> search-common
search-backend-module-pg --> search-backend-node/alpha
search-backend-module-pg --> search-backend
search-backend-module-stack-overflow-collator --> search-backend
search-backend-module-stack-overflow-collator --> search-common
search-backend-module-stack-overflow-collator --> search-backend-node/alpha
search-backend-module-techdocs --> search-backend
search-backend-module-techdocs --> catalog-node/testUtils
search-backend-module-techdocs --> catalog-common/alpha
search-backend-module-techdocs --> permission-common
search-backend-module-techdocs --> search-common
search-backend-module-techdocs --> techdocs
search-backend-module-techdocs --> catalog
search-backend-module-techdocs --> search-backend-node/alpha
search-backend-node --> search-common
search-backend-node --> search-backend
search-backend-node --> permission-common
search-common --> permission-common
search-react --> search-common
signals-backend --> signals
signals-backend --> events
signals-node --> events
techdocs --> techdocs-react/alpha
techdocs --> catalog
techdocs --> catalog-react/testUtils
techdocs --> search
techdocs --> techdocs-common
techdocs --> catalog-react/alpha
techdocs --> search-react/alpha
techdocs --> search-common
techdocs --> techdocs-module-addons-contrib
techdocs --> auth
techdocs-addons-test-utils --> techdocs
techdocs-addons-test-utils --> catalog
techdocs-addons-test-utils --> catalog-react/testUtils
techdocs-addons-test-utils --> search
techdocs-backend --> techdocs
techdocs-backend --> catalog
techdocs-backend --> catalog-node/testUtils
techdocs-module-addons-contrib --> techdocs
techdocs-module-addons-contrib --> techdocs-react/alpha
techdocs-module-addons-contrib --> techdocs-addons-test-utils
techdocs-module-addons-contrib --> catalog
techdocs-node --> techdocs-common
techdocs-node --> search-common
techdocs-react --> techdocs
techdocs-react --> techdocs-common
user-settings --> catalog
user-settings --> signals
user-settings --> user-settings-common
user-settings --> catalog-react/testUtils
user-settings-backend --> signals
user-settings-backend --> user-settings-common
